name: Update GitHub Contributions Image

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  push:
    branches:
      - master

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the GitHub contribution snake image (SVG)
      - name: Generate GitHub Contribution Snake Image
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contributions.svg

      # Step 3: Install dependencies for image conversion
      - name: Install rsvg-convert
        run: sudo apt-get install -y librsvg2-bin

      # Step 4: Convert SVG to PNG
      - name: Convert SVG to PNG
        run: |
          rsvg-convert -o dist/github-contributions.png dist/github-contributions.svg

      # Step 5: Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --local user.email "roberttk01@gmail.com"
          git config --local user.name "GitHub Actions"
          git add dist/
          git commit -m "Update GitHub contributions image (PNG)" || echo "No changes to commit"
          git push
