name: Generate Static GitHub Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  push:
    branches:
      - master

jobs:
  generate-graph:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch Contribution Graph using GitHub Stats API
      - name: Fetch Contribution Graph
        run: |
          curl "https://github-readme-stats.vercel.app/api?username=roberttk01&show_icons=true&theme=default" -o dist/github-contributions.png

      # Step 3: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --local user.email "roberttk01@gmail.com"
          git config --local user.name "GitHub Actions"
          git add dist/
          git commit -m "Update static GitHub contributions graph" || echo "No changes to commit"
          git push
